[build]
# Soroban contracts must be compiled for wasm32v1-none
target = "wasm32v1-none"

[target.wasm32v1-none]
rustflags = ["-C", "link-arg=-zstack-size=65536"]

[profile.release]
opt-level = "z"
overflow-checks = true
debug = 0
strip = "symbols"
debug-assertions = false
panic = "abort"
codegen-units = 1
lto = true
